import { useDB, exercises } from '../db'

export default defineEventHandler(async () => {
  const db = useDB()

  // Check if already seeded
  const existing = db.select().from(exercises).limit(1).all()
  if (existing.length > 0) {
    return { message: 'Database already seeded', count: existing.length }
  }

  const exerciseData = [
    // GLUTES — LOVED
    {
      name: 'Glute Bridge',
      slug: 'glute-bridge',
      category: 'glutes',
      musclePrimary: 'gluteus maximus',
      muscleSecondary: 'hamstrings',
      gifUrl: 'https://www.inspireusafoundation.org/wp-content/uploads/2022/01/glute-bridge.gif',
      description: 'Lie on your back, knees bent, feet flat. Push hips up, squeeze at top.',
      kidFriendlyTip: 'Teddy bear bridge! Push your tummy to the sky and squeeze a coin between your cheeks! 🧸',
      isAnkleSafe: true,
      equipment: 'mat',
      preference: 'loved',
      notes: 'His best exercise. Feels them well. Good form. 2-sec squeeze at top.',
    },
    {
      name: 'Single-Leg Glute Bridge',
      slug: 'single-leg-glute-bridge',
      category: 'glutes',
      musclePrimary: 'gluteus maximus',
      muscleSecondary: 'gluteus medius, hamstrings',
      gifUrl: 'https://www.inspireusafoundation.org/wp-content/uploads/2022/11/single-leg-glute-bridge.gif',
      description: 'One foot up as kickstand, push through other heel. Squeeze at top.',
      kidFriendlyTip: 'One-leg teddy bear! Put one foot up like a kickstand, push through the other heel. Squeeze that booty!',
      isAnkleSafe: true,
      equipment: 'mat',
      preference: 'loved',
      notes: 'Introduced Day 5 evening. GIF worked. 8-10 each side.',
    },
    {
      name: 'Frog Pumps',
      slug: 'frog-pumps',
      category: 'glutes',
      musclePrimary: 'gluteus medius',
      muscleSecondary: 'gluteus maximus',
      gifUrl: 'https://www.inspireusafoundation.org/wp-content/uploads/2023/08/frog-pump.gif',
      description: 'Soles together, knees wide. Push hips up and squeeze.',
      kidFriendlyTip: 'Froggy bounce! Sit like a frog — soles together, knees wide. Push up and squeeze like jumping to a lily pad! 🐸',
      isAnkleSafe: true,
      equipment: 'mat',
      preference: 'loved',
      notes: 'Introduced Day 4. GIF was initially wrong (meme). Correct GIF updated. Targets glute medius.',
    },
    {
      name: 'Sumo Squat',
      slug: 'sumo-squat',
      category: 'glutes',
      musclePrimary: 'gluteus maximus',
      muscleSecondary: 'quadriceps, adductors',
      gifUrl: 'https://www.inspireusafoundation.org/wp-content/uploads/2022/11/sumo-squat.gif',
      description: 'Wide stance, toes out. Squat down, push through heels.',
      kidFriendlyTip: 'Penguin pose! Open your feet wide, toes pointing out. Sit your butt DOWN like a tiny chair! Stand up — squeeze! 🐧',
      isAnkleSafe: true,
      equipment: 'none',
      preference: 'loved',
      notes: 'Knows them well. "Penguin" comparison works. Slight ankle load but manageable.',
    },
    {
      name: 'Donkey Kick',
      slug: 'donkey-kick',
      category: 'glutes',
      musclePrimary: 'gluteus maximus',
      muscleSecondary: 'hamstrings',
      gifUrl: 'https://www.inspireusafoundation.org/wp-content/uploads/2022/03/donkey-kick-exercise.gif',
      description: 'On all fours, kick one leg back and up. Squeeze at top.',
      kidFriendlyTip: 'Kitty cat kick! Get on all fours like a kitty. Kick one leg back like you\'re pushing a ball! Squeeze! 🐱',
      isAnkleSafe: true,
      equipment: 'mat',
      preference: 'loved',
      notes: 'Solid form. "Kitty cat" comparison works.',
    },
    // LEGS — LOVED
    {
      name: 'Wall Sit',
      slug: 'wall-sit',
      category: 'legs',
      musclePrimary: 'quadriceps',
      muscleSecondary: 'gluteus maximus',
      gifUrl: 'https://www.inspireusafoundation.org/wp-content/uploads/2022/03/wall-sit.gif',
      description: 'Back against wall, slide to 90°. Hold.',
      kidFriendlyTip: 'Invisible chair! Lean against the wall and sit on nothing! Hold it like you\'re a statue! 🧱',
      isAnkleSafe: true,
      equipment: 'wall',
      preference: 'loved',
      notes: 'PR tracking: 45s → 50s → 51s → 56s. Loves the PR tracking. Day 5: 56 sec record.',
    },
    {
      name: 'Wall Squat',
      slug: 'wall-squat',
      category: 'legs',
      musclePrimary: 'quadriceps',
      muscleSecondary: 'glutes',
      gifUrl: 'https://www.inspireusafoundation.org/wp-content/uploads/2022/03/wall-squat.gif',
      description: 'Back against wall, squat down and up. Controlled tempo.',
      kidFriendlyTip: 'Wall slide! Slide down, then push back up. Like an elevator for your booty!',
      isAnkleSafe: true,
      equipment: 'wall',
      preference: 'loved',
      notes: 'Done Day 5. Slow and controlled.',
    },
    // CORE — LOVED
    {
      name: 'Plank',
      slug: 'plank',
      category: 'core',
      musclePrimary: 'transverse abdominis',
      muscleSecondary: 'rectus abdominis, obliques',
      gifUrl: 'https://www.inspireusafoundation.org/wp-content/uploads/2022/01/plank.gif',
      description: 'Forearms and toes. Body straight. Hold.',
      kidFriendlyTip: 'Be a wooden board! Straight as a ruler from head to toes! Hold it tight!',
      isAnkleSafe: true,
      equipment: 'mat',
      preference: 'loved',
      notes: '45 sec solid. Core strength building. Did it Day 2.',
    },
    // GLUTES — OK
    {
      name: 'Side-Lying Leg Lift',
      slug: 'side-lying-leg-lift',
      category: 'glutes',
      musclePrimary: 'gluteus medius',
      muscleSecondary: 'hip abductors',
      gifUrl: 'https://www.inspireusafoundation.org/wp-content/uploads/2022/03/side-lying-leg-raise.gif',
      description: 'Lie on side, lift top leg. Control the descent.',
      kidFriendlyTip: 'Flag leg! Lie on your side and lift your top leg like raising a flag! 🏳️',
      isAnkleSafe: true,
      equipment: 'mat',
      preference: 'ok',
      notes: 'Does them well. Add pulse for progression (3 bounces at top). Introduced Day 1.',
    },
    {
      name: 'Side-Lying Leg Lift + Pulse',
      slug: 'side-lying-leg-lift-pulse',
      category: 'glutes',
      musclePrimary: 'gluteus medius',
      muscleSecondary: 'hip abductors',
      gifUrl: 'https://www.inspireusafoundation.org/wp-content/uploads/2022/03/side-lying-leg-raise.gif',
      description: 'Same as leg lift but add 3 tiny bounces at the top.',
      kidFriendlyTip: 'Same flag leg but with 3 tiny bounces at the top! Like your flag is fluttering in the wind! 🏳️',
      isAnkleSafe: true,
      equipment: 'mat',
      preference: 'loved',
      notes: 'He LOVED the pulse! "Those 3 little pulses do make the difference!!!" Introduced Day 5 evening.',
    },
    {
      name: 'Clam Shell',
      slug: 'clam-shell',
      category: 'glutes',
      musclePrimary: 'gluteus medius',
      muscleSecondary: 'hip external rotators',
      gifUrl: 'https://www.inspireusafoundation.org/wp-content/uploads/2022/03/clamshell-exercise.gif',
      description: 'Lie on side, knees bent, feet together. Open top knee like a clam.',
      kidFriendlyTip: 'Clammy! Lie on your side, feet together. Open your top knee like a clam opening its shell! 🐚',
      isAnkleSafe: true,
      equipment: 'mat',
      preference: 'ok',
      notes: 'Introduced Day 3. No issues.',
    },
    {
      name: 'Fire Hydrant',
      slug: 'fire-hydrant',
      category: 'glutes',
      musclePrimary: 'gluteus medius',
      muscleSecondary: 'hip abductors',
      gifUrl: 'https://www.inspireusafoundation.org/wp-content/uploads/2022/11/fire-hydrant-exercise.gif',
      description: 'On all fours, lift one knee out to the side. Like a dog at a fire hydrant.',
      kidFriendlyTip: 'Doggy lift! On all fours, lift your knee out to the side like a puppy! 🐕',
      isAnkleSafe: true,
      equipment: 'mat',
      preference: 'ok',
      notes: 'Introduced Day 1. Knows the movement.',
    },
    {
      name: 'Bird Dog',
      slug: 'bird-dog',
      category: 'core',
      musclePrimary: 'erector spinae',
      muscleSecondary: 'glutes, core',
      gifUrl: 'https://www.inspireusafoundation.org/wp-content/uploads/2022/02/bird-dog.gif',
      description: 'On all fours, extend opposite arm and leg. Hold. Switch.',
      kidFriendlyTip: 'Bird-dog! One arm forward, opposite leg back — like a bird AND a dog at the same time! 🦮',
      isAnkleSafe: true,
      equipment: 'mat',
      preference: 'ok',
      notes: 'Planned as dead bug replacement. Day 5 evening.',
    },
    // FLEXIBILITY
    {
      name: 'Lying Hip Flexor Stretch',
      slug: 'lying-hip-flexor-stretch',
      category: 'flexibility',
      musclePrimary: 'hip flexors',
      muscleSecondary: 'quadriceps',
      gifUrl: 'https://www.inspireusafoundation.org/wp-content/uploads/2022/02/lying-hip-flexor-stretch.gif',
      description: 'Lie on side, bend knee, pull heel to butt. Hold.',
      kidFriendlyTip: 'Catch your heel! Lie on your side, bend your knee, and try to catch your heel with your hand! Hold it! 🦶',
      isAnkleSafe: true,
      equipment: 'mat',
      preference: 'loved',
      notes: 'REPLACES kneeling hip flexor stretch. Kneeling version hurts ankle.',
    },
    {
      name: 'Lying Figure-4 Stretch',
      slug: 'lying-figure-4-stretch',
      category: 'flexibility',
      musclePrimary: 'piriformis, glutes',
      muscleSecondary: 'hip rotators',
      gifUrl: 'https://www.inspireusafoundation.org/wp-content/uploads/2022/03/lying-piriformis-stretch.gif',
      description: 'Lie on back, cross ankle over opposite knee. Pull toward chest.',
      kidFriendlyTip: 'Number 4! Make a number 4 with your legs, then pull your bottom leg toward you!',
      isAnkleSafe: true,
      equipment: 'mat',
      preference: 'loved',
      notes: 'REPLACES pigeon pose. Pigeon hurt lower back Day 2.',
    },
    {
      name: 'Hamstring Stretch',
      slug: 'hamstring-stretch',
      category: 'flexibility',
      musclePrimary: 'hamstrings',
      muscleSecondary: 'calves',
      gifUrl: 'https://www.inspireusafoundation.org/wp-content/uploads/2022/03/standing-hamstring-stretch.gif',
      description: 'Sit with one leg extended, reach toward toes. Hold.',
      kidFriendlyTip: 'Reach for your toes! Like trying to touch your shoelaces without bending your knee!',
      isAnkleSafe: true,
      equipment: 'mat',
      preference: 'ok',
      notes: 'Part of cool-down routine.',
    },
    {
      name: 'Quad Stretch',
      slug: 'quad-stretch',
      category: 'flexibility',
      musclePrimary: 'quadriceps',
      muscleSecondary: 'hip flexors',
      gifUrl: 'https://www.inspireusafoundation.org/wp-content/uploads/2022/02/standing-quad-stretch.gif',
      description: 'Stand on one leg, pull other heel to butt. Hold.',
      kidFriendlyTip: 'Catch your heel behind you! Stand on one leg and pull the other heel to your booty!',
      isAnkleSafe: true,
      equipment: 'none',
      preference: 'ok',
      notes: 'Part of cool-down routine.',
    },
    {
      name: 'Happy Baby Pose',
      slug: 'happy-baby-pose',
      category: 'flexibility',
      musclePrimary: 'hip flexors, adductors',
      muscleSecondary: 'lower back',
      gifUrl: 'https://www.inspireusafoundation.org/wp-content/uploads/2022/02/happy-baby-pose.gif',
      description: 'Lie on back, grab feet, knees toward armpits. Rock gently.',
      kidFriendlyTip: 'Happy baby! Lie on your back, grab your feet, and rock like a happy baby! 👶',
      isAnkleSafe: true,
      equipment: 'mat',
      preference: 'loved',
      notes: 'Preferred over child\'s pose. His preferred final stretch.',
    },
    // HATED
    {
      name: 'Dead Bug',
      slug: 'dead-bug',
      category: 'core',
      musclePrimary: 'transverse abdominis',
      muscleSecondary: 'rectus abdominis',
      gifUrl: 'https://www.inspireusafoundation.org/wp-content/uploads/2022/01/dead-bug-exercise.gif',
      description: 'Lie on back, arms up, knees at 90°. Extend opposite arm/leg.',
      kidFriendlyTip: 'Dead bug! Lie on your back and wave your arms and legs like an upside-down bug!',
      isAnkleSafe: true,
      equipment: 'mat',
      preference: 'hated',
      notes: 'HATED since Day 1. Tried twice. DO NOT PROGRAM. Use bird dogs or plank instead.',
    },
    // FUTURE CANDIDATES
    {
      name: 'Stomach Vacuum',
      slug: 'stomach-vacuum',
      category: 'core',
      musclePrimary: 'transverse abdominis',
      muscleSecondary: '',
      gifUrl: '',
      description: 'Exhale all air, pull belly button to spine. Hold.',
      kidFriendlyTip: 'Belly button kiss! Pull your tummy in like you\'re trying to touch your backbone! Hold tight!',
      isAnkleSafe: true,
      equipment: 'none',
      preference: 'untested',
      notes: 'Research candidate. Targets transverse abdominis for waist sculpting. 3-5 rounds of 10-15 sec holds.',
    },
    {
      name: 'Standing Glute Kickback',
      slug: 'standing-glute-kickback',
      category: 'glutes',
      musclePrimary: 'gluteus maximus',
      muscleSecondary: 'hamstrings',
      gifUrl: 'https://www.inspireusafoundation.org/wp-content/uploads/2022/03/glute-kickback.gif',
      description: 'Stand on one leg, kick other straight back. Squeeze at top.',
      kidFriendlyTip: 'Fancy horse! Stand tall, kick one leg straight back like closing a door with your heel! 🐴',
      isAnkleSafe: true,
      equipment: 'none',
      preference: 'untested',
      notes: 'Research candidate. Pure glute max isolation.',
    },
    {
      name: 'Prone Hip Extension',
      slug: 'prone-hip-extension',
      category: 'glutes',
      musclePrimary: 'gluteus maximus',
      muscleSecondary: 'lower back',
      gifUrl: 'https://www.inspireusafoundation.org/wp-content/uploads/2022/03/prone-hip-extension.gif',
      description: 'Lie face down, lift one straight leg. Alternate.',
      kidFriendlyTip: 'Superman leg! Lie on your tummy and kick one straight leg up toward the ceiling! 🦸',
      isAnkleSafe: true,
      equipment: 'mat',
      preference: 'untested',
      notes: 'Research candidate. Hits glutes AND lower back.',
    },
    {
      name: 'Ankle Circle',
      slug: 'ankle-circle',
      category: 'flexibility',
      musclePrimary: 'ankle joint',
      muscleSecondary: 'calves',
      gifUrl: '',
      description: 'Lift foot, draw circles with toes.',
      kidFriendlyTip: 'Tiny pot of soup! Stir a tiny pot with your toes! 10 circles each way! 🍲',
      isAnkleSafe: true,
      equipment: 'none',
      preference: 'loved',
      notes: 'Good for healing ankle. Part of warm-up.',
    },
    {
      name: 'Seated Glute Squeeze',
      slug: 'seated-glute-squeeze',
      category: 'glutes',
      musclePrimary: 'gluteus maximus',
      muscleSecondary: '',
      gifUrl: '',
      description: 'Squeeze butt cheeks together, hold, release.',
      kidFriendlyTip: 'Coin squeeze! Hold a coin between your cheeks! 3 seconds each! 🥜',
      isAnkleSafe: true,
      equipment: 'chair',
      preference: 'ok',
      notes: 'Desk exercise. Invisible to coworkers. Introduced Day 6 (Apr 1).',
    },
    {
      name: 'Seated Marching',
      slug: 'seated-marching',
      category: 'legs',
      musclePrimary: 'hip flexors',
      muscleSecondary: 'quadriceps',
      gifUrl: '',
      description: 'Lift one knee toward chest, hold 2 sec, switch.',
      kidFriendlyTip: 'Tiny parade! March in your chair — lift that knee and hold! 🥁',
      isAnkleSafe: true,
      equipment: 'chair',
      preference: 'ok',
      notes: 'Desk exercise. Introduced Day 6 (Apr 1).',
    },
    {
      name: 'Seated Knee Extension',
      slug: 'seated-knee-extension',
      category: 'legs',
      musclePrimary: 'quadriceps',
      muscleSecondary: '',
      gifUrl: '',
      description: 'Straighten one leg, squeeze quad, hold 3 sec.',
      kidFriendlyTip: 'Point your toes! Straighten your leg like you\'re pointing at something far away! 🦵',
      isAnkleSafe: true,
      equipment: 'chair',
      preference: 'ok',
      notes: 'Desk exercise. Introduced Day 6 (Apr 1).',
    },
    {
      name: 'Glute Bridge on Chair',
      slug: 'glute-bridge-chair',
      category: 'glutes',
      musclePrimary: 'gluteus maximus',
      muscleSecondary: 'hamstrings',
      gifUrl: '',
      description: 'Edge of chair, grip seat, push hips up, squeeze.',
      kidFriendlyTip: 'Chair bridge! Scoot to the edge and push your booty to the sky! Squeeze! 🪑',
      isAnkleSafe: true,
      equipment: 'chair',
      preference: 'ok',
      notes: 'Desk exercise. Introduced Day 6 (Apr 1).',
    },
    {
      name: 'Seated Torso Twist',
      slug: 'seated-torso-twist',
      category: 'core',
      musclePrimary: 'obliques',
      muscleSecondary: 'spinal rotators',
      gifUrl: '',
      description: 'Hands on shoulders, twist upper body left and right.',
      kidFriendlyTip: 'Washing machine! Twist your body left and right like you\'re spinning! 🌀',
      isAnkleSafe: true,
      equipment: 'chair',
      preference: 'ok',
      notes: 'Warm-up exercise. Introduced Day 6 (Apr 1).',
    },
  ]

  const inserted = db.insert(exercises).values(exerciseData).run()

  // Seed achievements
  const achievementData = [
    { slug: 'first-session', name: 'First Steps', description: 'Complete your first training session', icon: '👶' },
    { slug: 'wall-sit-30', name: 'Wall Warrior', description: 'Hold a wall sit for 30 seconds', icon: '🧱' },
    { slug: 'wall-sit-45', name: 'Wall Master', description: 'Hold a wall sit for 45 seconds', icon: '🏰' },
    { slug: 'wall-sit-60', name: 'Wall Legend', description: 'Hold a wall sit for 60 seconds', icon: '👑' },
    { slug: 'glute-bridge-60', name: 'Bridge Builder', description: 'Hold a glute bridge for 60 seconds', icon: '🌉' },
    { slug: 'plank-30', name: 'Core Rookie', description: 'Hold a plank for 30 seconds', icon: '💪' },
    { slug: 'plank-60', name: 'Core Warrior', description: 'Hold a plank for 60 seconds', icon: '🔥' },
    { slug: 'streak-3', name: 'Consistency King', description: 'Train 3 days in a row', icon: '👑' },
    { slug: 'streak-7', name: 'Week Warrior', description: 'Train 7 days in a row', icon: '⚡' },
    { slug: 'pr-breaker', name: 'PR Breaker', description: 'Break any personal record', icon: '🏆' },
    { slug: 'glute-expert', name: 'Glute Obsessed', description: 'Complete 10 glute-focused sessions', icon: '🍑' },
    { slug: 'flexibility-gain', name: 'Bendy', description: 'Improve any flexibility measurement', icon: '🧘' },
  ]

  const { achievements: achievementsTable } = await import('../db/schema')
  db.insert(achievementsTable).values(achievementData).run()

  return {
    message: 'Database seeded successfully!',
    exercises: exerciseData.length,
    achievements: achievementData.length,
  }
})
